[build]
builder = "dockerfile"
dockerfilePath = "client/Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/"
healthcheckPort = 8080
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production" 