version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: build
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - FRONTEND_URL=https://puzzlemakeribral-production.up.railway.app
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev 