[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npm install"]

[start]
cmd = "cd backend && NODE_ENV=production PORT=3000 node src/index.js" 