[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = ""  # Explicitly disable any automatic build steps

[deploy]
startCommand = "node src/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production" 