[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node src/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production" 